name: Download
on:
  workflow_dispatch:
jobs:
  Download:
    name: Download
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Download
        run: |
          mkdir ./download
          wget -O ./download/PixelOS_sweet-14.0-20240628-1702.zip "https://master.dl.sourceforge.net/project/pixelos-releases/fourteen/sweet/PixelOS_sweet-14.0-20240628-1702.zip?viasf=1"
      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: |
            ./download/*.zip
          name: Download
          tag: all
          allowUpdates: true
